name: updates
on:
  schedule:
    - cron: '0 4 * * *'
permissions: write-all
  # contents: read

jobs:
  alarms-fig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: run themadad script
      run: |
        python -W ignore seqer.py
    - name: check news
      run: |
        git config --global user.name "actions"
        git config --global user.email "actions@github"
        if [ -n "$(git status --porcelain)" ]; then
          echo "IS_NEW=true" >> $GITHUB_ENV
        else
          echo "no changes"
          echo "IS_NEW=false" >> $GITHUB_ENV
        fi
    - name: commit files
      run: |
        git add -A
        git commit -m "daily update"
        git pull
      if: ${{ env.IS_NEW == 'true' }}
    - name: push files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ env.IS_NEW == 'true' }}
